name: Check for broken links

on: [deployment_status]

jobs:
  check-links:
    name: check broken links
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        run: ./scripts/checkLinks.sh
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}
